version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    privileged: true
    command: /sbin/init
    ports:
      - "80:80"
      - '443:443'
    depends_on:
      - ap
    networks:
      custom_net:
        ipv4_address: 172.28.10.2

  ap:
    build: ./ap
    container_name: ap
    privileged: true
    command: /sbin/init
    networks:
      custom_net:
        ipv4_address: 172.28.10.3
  
  mysqlrouter_ra:
    build: ./db
    container_name: mysqlrouter_ra
    privileged: true
    command: /sbin/init
    networks:
      custom_net:
        ipv4_address: 172.28.10.6
  
  mysqlrouter_rb:
    build: ./db
    container_name: mysqlrouter_rb
    privileged: true
    command: /sbin/init
    networks:
      custom_net:
        ipv4_address: 172.28.10.7
  
  db1:
    build: ./db
    container_name: db1
    privileged: true
    command: /sbin/init
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    networks:
      custom_net:
        ipv4_address: 172.28.10.8
  
  db2:
    build: ./db
    container_name: db2
    privileged: true
    command: /sbin/init
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    networks:
      custom_net:
        ipv4_address: 172.28.10.9

  db3:
    build: ./db
    container_name: db3
    privileged: true
    command: /sbin/init
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3308:3306"
    networks:
      custom_net:
        ipv4_address: 172.28.10.10

  nagios:
    build: ./nagios
    container_name: nagios
    privileged: true
    command: /sbin/init
    ports:
      - "8081:80"
    networks:
      custom_net:
        ipv4_address: 172.28.10.11

  smtp:
    build: ./ap
    container_name: smtp
    privileged: true
    command: /sbin/init
    ports:
      - "2525:25"
    networks:
      custom_net:
        ipv4_address: 172.28.10.12

  dns:
    build: ./ap
    container_name: dns
    privileged: true
    command: /sbin/init
    networks:
      custom_net:
        ipv4_address: 172.28.10.13
  
  ansible:
    build: ./ap
    container_name: ansible
    privileged: true
    command: /sbin/init
    networks:
      custom_net:
        ipv4_address: 172.28.10.14
  
  nfs:
    build: ./ap
    container_name: nfs
    privileged: true
    command: /sbin/init
    networks:
      custom_net:
        ipv4_address: 172.28.10.15

  # ftp:
  #   build: ./ap
  #   container_name: ap
  #   privileged: true
  #   command: /sbin/init
  #   networks:
  #     custom_net:
  #       ipv4_address: 172.28.10.6

#htaccess
#modsec
#basic認証
#logrotate
#drbd

networks:
  custom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1